image: node:latest

test:
  only:
    - master
  script:
    - yarn
    - yarn lerna-build
    - yarn test

publish:
  stage: deploy
  only:
    - web
    - /^v.*$/
  except:
    - branches
  script:
    - echo "Starting NPM Deploy"
    - export NODE_ENV=dev && echo $NODE_ENV
    - NPM_USER=$NPM_USER NPM_PASS=$NPM_PASS NPM_EMAIL=$NPM_EMAIL NPM_REGISTRY=$NPM_REGISTRY NPM_SCOPE=@ssgw npx npm-cli-adduser
    - npm run npm-publish
