image: node:latest

variables:
  DEV_SERVER: 'within.sg.rgadev.com'
  DEV_URL: 'http://within.sg.rgadev.com'

test:
  only:
    - master
  script:
    - yarn
    - yarn lerna-build
    - yarn test

publish:
  stage: deploy
  only:
    - web
    - /^v.*$/
  except:
    - branches
  script:
    - echo "Starting NPM Deploy"
    - export NODE_ENV=dev && echo $NODE_ENV
    - NPM_USER=$NPM_USER NPM_PASS=$NPM_PASS NPM_EMAIL=$NPM_EMAIL NPM_REGISTRY=$NPM_REGISTRY NPM_SCOPE=@ssgw npx npm-cli-adduser
    - npm run npm-publish

storybook:
  stage: deploy
  only:
    - master
  except:
    - /^v.*$/
  script:
    - yarn
    - yarn lerna-build
    - yarn build-storybook
    - echo "Deploy build to s3"
    - apt-get update
    - apt-get install -y awscli
    - mkdir -p ~/.aws/
    - printf "[default]\naws_access_key_id=$AWS_ACCESS_KEY_ID\naws_secret_access_key=$AWS_SECRET_ACCESS_KEY\n" > ~/.aws/credentials;
    - printf "[default]\nregion=$AWS_REGION\n" > ~/.aws/config;
    - find ./storybook-static -type f
    - aws s3 sync ./storybook-static s3://${AWS_BUCKET_NAME}${AWS_BUCKET_FOLDER} --delete
